apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: aliases
        configMap:
          name: {{ template "rucio.fullname" . }}-aliases
      - name: httpdlog
        emptyDir: {}
      - name: hostcert
        secret:
          secretName: {{ .Release.Name }}-hostcert
      - name: hostkey
        secret:
          secretName: {{ .Release.Name }}-hostkey
      - name: cafile
        secret:
          secretName: {{ .Release.Name }}-cafile
      {{- range $key, $val := .Values.additionalSecrets }}
      - name: {{ $key }}
        secret:
          secretName: {{ $.Release.Name }}-{{ $val.secretName }}
      {{- end}}
      {{- range $key, $val := .Values.persistentVolumes }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $val.name }}
      {{- end}}
      containers:
{{- if .Values.exposeErrorLogs }}
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -f /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
{{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpdlog
              mountPath: /var/log/httpd
            - name: aliases
              mountPath: /opt/rucio/etc/aliases.conf
              subPath: aliases.conf
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
            {{- range $key, $val := .Values.additionalSecrets }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
              subPath: {{ $val.subPath }}
            {{- end}}
            {{- range $key, $val := .Values.persistentVolumes }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
            {{- end}}
          env:
            {{- range $key1, $val1 := .Values.config }}
            {{- range $key2, $val2 := $val1}}
            - name: RUCIO_CFG_{{ $key1 | upper }}_{{ $key2 | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "rucio.fullname" $ }}.cfg
                  key: {{ $key1 }}_{{ $key2 }}
            {{- end}}
            {{- end}}

            {{- range $key1, $val1 := .Values.optional_config }}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
            {{- end}}

            - name: RUCIO_PROXY
              value: {{ .Values.proxy.rucioProxy }}
            - name: RUCIO_AUTH_PROXY
              value: {{ .Values.proxy.rucioAuthProxy }}
{{- if .Values.proxy.rucioProxyScheme }}
            - name: RUCIO_PROXY_SCHEME
              value: {{ .Values.proxy.rucioProxyScheme }}
{{- end }}
{{- if .Values.proxy.rucioAuthProxyScheme }}
            - name: RUCIO_AUTH_PROXY_SCHEME
              value: {{ .Values.proxy.rucioAuthProxyScheme }}
{{- end }}
            - name: RUCIO_DEFINE_ALIASES
              value: "True"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
